### PR TITLE
Add git-next-release script

### PR DESCRIPTION
**Pull request by euriconicacio**
Add script to list branches merged into main that will be included in a new build/release in a Slack-friendly format.

Tested on a daily basis execution. 🙃

### CODE REVIEW

**Comment by bicschneider** [comment]
Hi ..
thanks for opening a pull request .. It is not the correct place to paste as the analyses a repo where you script is related to releasing.. 

Can you enlighten, how you see the future of your script?

**Comment by euriconicacio** [comment]
Hi!
Thanks for the review! I am sorry for the mistake, in fact, the subjects are distinct. Is there another path where you think this script would fit better? Maybe `small-git-tricks` or `misc`?
In addition, concerning the future of the script, it can be evolved for different messaging platforms templates, or be adapted for different events, for example. Basically, it is a handy piece of code I always add to my Makefiles. 🙂

**Comment by euriconicacio** [comment]
Hi, @bicschneider .

Any further guidance on this? Should I change it some way or even drop it?

Sorry for bothering and thanks in advance!

**Comment by euriconicacio** [comment]
Hi, @bicschneider . Should I close this PR?

**Pull request closed without merging**
